# Generated by Django 4.2.16 on 2024-12-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
