# Generated by Django 4.2.16 on 2024-12-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_transcript_error_message_transcript_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='status',
        ),
    ]
