# Generated by Django 4.2.16 on 2024-12-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_transcript_transcript_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='search',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
