# Generated by Django 4.2.17 on 2024-12-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_searchquery_transcript_search_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='summary_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
