# Generated by Django 4.2.17 on 2024-12-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_transcript_summary_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='search_date',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='summary_text',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='combined_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='search_query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.searchquery'),
        ),
    ]
