# Generated by Django 4.2.17 on 2025-01-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_searchquery_search_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='guide_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
