# Generated by Django 4.2.17 on 2025-02-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_searchquery_guide_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='guide_pdf',
            field=models.FileField(blank=True, null=True, upload_to='guides/'),
        ),
    ]
