# Generated by Django 4.2.17 on 2025-02-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_searchquery_guide_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='guide_pdf',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
