# Generated by Django 4.2.17 on 2025-02-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_searchquery_guide_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='pdf_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
