# Generated by Django 4.2.17 on 2025-03-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='admin@example.com', max_length=254, unique=True)),
                ('password', models.CharField(default='admin1234', max_length=100)),
            ],
        ),
    ]
